# Generated by Django 4.2.10 on 2024-02-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0005_delete_apilogsmodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILogsModel2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('api', models.CharField(help_text='API URL', max_length=1024)),
                ('headers', models.TextField()),
                ('body', models.TextField()),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('client_ip_address', models.CharField(max_length=50)),
                ('response', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, help_text='Response status code')),
                ('execution_time', models.DecimalField(decimal_places=5, help_text='Server execution time (Not complete response time.)', max_digits=8)),
                ('added_on', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'db_table': 'drf_api_logs2',
            },
        ),
    ]
